POST http://localhost:3000/logs/accesslogs
Content-Type: application/json
Authorization: eyJraWQiOiJVbHJNRFhNU3JLYVwvU1NrOFBnVDdtNmxPTTBuaVdZdHE4MTQ5Nk55VGl0RT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJmOTFhN2M0Ny1lZTdiLTQ2NGItYTk4ZS0zZmRlZmM5MDk4YzQiLCJldmVudF9pZCI6IjgzMzg5ZmI0LWM5YmItNGZiMS04ZmYwLWVhYTRmZDJkMjI1ZiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE1OTUzNTc2MjUsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5hcC1zb3V0aC0xLmFtYXpvbmF3cy5jb21cL2FwLXNvdXRoLTFfWnpESWh0Q1VuIiwiZXhwIjoxNTk1MzYxMjI1LCJpYXQiOjE1OTUzNTc2MjUsImp0aSI6IjVkODg0NTllLTA5NDYtNDE5ZC04NGMzLWNhMGQxZGM4MTcxZCIsImNsaWVudF9pZCI6IjJxMG5vbHRiczk4bHQ5MWNkMTU2M2pwMXBuIiwidXNlcm5hbWUiOiJzaGFoYmF6MSJ9.NcFZWWVdvoCHue-hlPigeyBkqb5R79lk74rjGcCYqeAl1AA6mPkAcBFdyvubNksJdy9tdcLDrfYwJQDoyvUVwyYF0u3RhjDKHsX2do0OSWH43Vsq96sREoqGOfB0a57PERO4Bqod2oMaoCRAhlrm1F-lq01C9jjpKEWF2gp19Kuw2z3TmIrSSK1M-n5s-bnvwiM9MFi6tJJWR9fPX5r-M4rOmfGcD3Z2oP0fG29Pz6igVWsTkhx-0V3gtzH7N-TDvC6GRoqXT3UUw3m5D9UHGuGTv4MbX5X7tqC1dhQm5XTtFSB7IazmO77DSLPzCgm15bCg_jAwj-ogkEjqhn0-RA


{
  "idx":"1"
}